name: Cache and Required Step Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Cache dependencies (required step)
      - name: prime-cache-89f785d
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-89f785d

      # Step 3: Print cache hit/miss
      - name: Check cache hit/miss
        run: |
          if [ "${{ steps.cache-step.outputs.cache-hit }}" == "true" ]; then
            echo "Cache hit"
          else
            echo "Cache miss"
          fi

      # Step 4: Required step with your email
      - name: 24f2005753@ds.study.iitm.ac.in
        run: echo "Hello, world!"
