name: Test Workflow

on:
  workflow_dispatch:  # allows manual trigger

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 24f2005753@ds.study.iitm.ac.in
        run: echo "Hello, world!"
